feat(searchbox): onValueSelected callback and value-selected event
appbaseio/Docs pull request #112
Opened 2020-02-06 11:43 UTC by ShahAnuj2610

2020-02-06 15:53 UTC, jyash97 approved these changes

2020-04-08 03:51 UTC, bietkul approved these changes

2020-04-08 03:51 UTC, bietkul commented
@ShahAnuj2610 What about the `searchbox`, do we not have `onValueSelected` there?

2020-04-08 03:52 UTC, bietkul requested changes
@ShahAnuj2610 What about the searchbox, do we not have onValueSelected there?

2020-04-09 11:37 UTC, ShahAnuj2610 commented
> @ShahAnuj2610 What about the searchbox, do we not have onValueSelected there?

no, we don't have it in searchbox. It has events related to `autocomplete.js` library

2020-04-13 06:58 UTC, merged