feat(searchbox): appbaseConfig prop for analytics
appbaseio/Docs pull request #131
Opened 2020-04-07 11:04 UTC by ShahAnuj2610

2020-04-07 12:29 UTC, bietkul requested changes

2020-04-07 12:29 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +    Read more about it over [here](/docs/reactivesearch/v3/advanced/analytics/#configure-the-analytics-experience).
@ShahAnuj2610 We need to define the properties here, not all properties are present here.

2020-04-07 12:29 UTC, bietkul commented on content/docs/reactivesearch/searchbase/overview/apireference.md
> +    appbaseConfig: {
@ShahAnuj2610 Use all options in the examples.

2020-04-07 12:29 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +	appbaseConfig={{ recordAnalytics: true }}
@ShahAnuj2610 Use all options.

2020-04-07 12:29 UTC, bietkul commented on content/docs/reactivesearch/vue-searchbox/apireference.md
> +	:appbaseConfig="{
same here

2020-04-07 12:29 UTC, bietkul commented on content/docs/reactivesearch/vue-searchbox/apireference.md
> +    Read more about it over [here](/docs/reactivesearch/v3/advanced/analytics/#configure-the-analytics-experience).
same here

2020-04-07 20:57 UTC, siddharthlatest approved these changes

2020-04-07 20:58 UTC, siddharthlatest approved these changes

2020-04-07 20:58 UTC, merged

2020-04-08 05:01 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +        userId: '192.168.0.102',
@ShahAnuj2610 It shouldn't be the `IP`, it should be like `jon@appbase.io`.

2020-04-08 05:01 UTC, bietkul commented on content/docs/reactivesearch/searchbase/overview/apireference.md
> +        userId: '192.168.0.102',
@ShahAnuj2610 Update

2020-04-08 05:01 UTC, bietkul commented on content/docs/reactivesearch/vue-searchbox/apireference.md
> +        userId: '192.168.0.102',
@ShahAnuj2610 Update