React SearchBox documentation
appbaseio/Docs pull request #157
Opened 2020-09-17 12:40 UTC by nikhil-varma

2020-09-18 03:36 UTC, bietkul requested changes

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
>      refers to an `index` if you’re using your own Elasticsearch cluster. If you're using an appbase.io hosted app, then the app name can be used.
@nikhil-varma `SearchBase` is not for apps, check the content in `SearchBase`.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
>      If you are using an appbase.io app, you will find credentials under your [API credentials page](https://dashboard.appbase.io/app?view=credentials). If you are not using an appbase.io app, credent
It should be `If you are using an appbase.io cluster`

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **SearchBase**: It is used as an internal dependency to connect with an Elastic Search system to perform search queries)
@nikhil-varma Why is there a bracket in the end?

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **SearchBox**: The core of the library which helps with data access and manipulation with any UI components
The definition is not correct. It should be described as a search input component to perform. For ref. check the `DataSearch` docs.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **SearchComponent**: The essential headless component for implement and integrating custom UI blocks seamlessly
What do you mean by `headless` here?
It is a component to integrate any kind of `ES` query to your UI blocks.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **SearchBase**: It is used as an internal dependency to connect with an Elastic Search system to perform search queries)
@nikhil-varma It is a provider component that provides the `searchbase` context to the child components.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +This is used as an internal dependency to connect with an Elastic Search system to perform search queries. This allows adding details related to the Elastic Search system like `index`, `crendentials`
Please mention it as a context provider. Also mention how one can access the `searchbase` instance from the context that we're exporting from lib.

It is missing an example, usage is not clear from the docs.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **transformResponse** `Function` Enables transformation of search network response before
@nikhil-varma Define example

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +-   **transformRequest** `Function` Enables transformation of network request before
@nikhil-varma Define example

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +The core of the library which helps with data access and manipulation with any UI components
@nikhil-varma Update definition, please refer to the old docs.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/apireference.md
> +### Props
@nikhil-varma Can you break props into sections?
Ref. `SearchBase` docs PR
Also, add examples for non-intuitive props, for e.g `defaultSuggestions`.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/quickstart.md
> +## Basic Usage
@nikhil-varma This example should also render the search results.

2020-09-18 03:36 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/quickstart.md
> +## Result
The title should be an example with a facet

2020-09-20 16:21 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/apireference.md
>      If you are using an appbase.io app, you will find credentials under your [API credentials page](https://dashboard.appbase.io/app?view=credentials). If you are not using an appbase.io app, credent
@nikhil-varma All app specific docs here should be removed. And url shouldn't default to `https://scalr.api.appbase.io` as well.

2020-09-20 16:35 UTC, siddharthlatest requested changes

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/quickstart.md
> +[react-searchbox](https://github.com/appbaseio/react-searchbox) - React SearchBox is a standalone, lightweight search library which allows you to add custom UI components and allow seamless search sy
```suggestion
[react-searchbox](https://github.com/appbaseio/react-searchbox) - React Searchbox is a lightweight search library (30KB gzipped size) for quickly creating search experiences powered by Elasticsearch. It takes care of querying to Elasticsearch, managing search state and updating your search UI. Searchbox is built with ease of integration with any design system in mind.
```

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/quickstart.md
> +[react-searchbox](https://github.com/appbaseio/react-searchbox) - React SearchBox is a standalone, lightweight search library which allows you to add custom UI components and allow seamless search sy
I've edited this. See if this sounds better. We can make changes to this for better accuracy.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbase.md
> +meta_description: 'SearchBase is a lightweight and platform agnostic search library for Elasticsearch.'
Wrong meta description. It's a component. We went over this distinction in the last call.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbase.md
> +It is a container component that wraps all the ReactiveSearch components together. It binds the backend app (data source) with the UI view components
```suggestion
`SearchBase` is a container component that wraps all the Searchbox components together. It binds the backend index (data source) with the UI view components.
```

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbase.md
> +It is a container component that wraps all the ReactiveSearch components together. It binds the backend app (data source) with the UI view components
@nikhil-varma When you copy from other docs, make sure to edit for context of the current doc.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbase.md
> +(elements wrapped within ReactiveBase), allowing a UI component to be reactively updated every time there is a change in the data source or in other UI components.
@nikhil-varma Same here. There is no `ReactiveBase`.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbase.md
> +-   **index** `string` [required]
@nikhil-varma Refer to Searchbase docs for the prop defintions.

Environment should be without (s) suffix.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +SearchBox offers a lightweight and performance focused searchbox UI component to query and display results from your Elasticsearch cluster.
Use the definition from the updated Searchbase doc PR.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +#### To configure the SearchBox API
What is the SearchBox API?

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +    > This prop is optional only when `enableAppbase` prop is set to `true`.
@bietkul There shouldn't be any `enableAppbase` prop for this library.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **size** `number` To set the number of results to be returned by a query.
@nikhil-varma There are formatting differences b/w the prop whitespaces (description is on next line in Searchbase API ref v/s same line over here)

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +*   **onError** `Function` gets triggered in case of an error while fetching results
Why are we using different bullet point chars? `-` above and `*` here.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchcomponent.md
> +meta_description: 'React SearchBox is a lightweight react search library with some common utilities.'
@nikhil-varma Meta description should be specific to the page.

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchcomponent.md
> +#### To configure the Appbase environments
remove suffix (s)

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchcomponent.md
> +#### To configure the Appbase environments
Redundant article "the"

2020-09-20 16:35 UTC, siddharthlatest commented on content/docs/reactivesearch/react-searchbox/searchcomponent.md
> +-   **index** `string` [required]
For all the props, refer to the issues highlighted in the SearchBox documentation review.

2020-09-21 14:36 UTC, closed without merging