feat: add docs for cache management
appbaseio/Docs pull request #182
Opened 2021-04-09 06:17 UTC by bietkul

2021-04-12 23:01 UTC, siddharthlatest commented
@bietkul 

- [ ] The icon doesn't match other icons, you can use one that does. The spacing isn't even.

![](https://i.imgur.com/5LQyZl2.png)

- [ ] Positioning change is needed in the top area as well. Also change `Security Credentials` to `Security`.

![](https://i.imgur.com/Q5IbgTF.png)

2021-04-13 00:11 UTC, siddharthlatest requested changes

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/search/reactivesearch-api/reference.md
> +This property allows you to cache the search requests. The `useCache` property has the higher precedence over the cache preferences. If it is defined in the request body then no matter what are your
```suggestion
`Boolean` This property when set allows you to cache the current search query. The `useCache` property takes precedence irrespective of whether caching is enabled or disabled via the dashboard.
```

2021-04-13 00:11 UTC, siddharthlatest commented on src/pages/index.js
> +										title: 'Speed',
@bietkul This should come before Security section.

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +![alt cache preferences GUI](https://i.imgur.com/L7P3NYx.png)
@bietkul Use the new image. Also update the image we use for the lock screen in the dashboard.

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +The time to live for a cached request in seconds. The default value is 360s. Cache Duration must be in a range of 60s to 3600s(1 hr).
@bietkul The default value is 300s, not 360s.

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +The memory limit for the cached requests in MB(s). The default value is 128MB. It can go up to 4000MB(4GB). Appbase.io uses a cache eviction policy to remove costly requests automatically once it rea
@bietkul What is the eviction policy based on? Mentioning that is an important detail.

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +Appbase.io sets the `x-request-cache` header as `true` for cached responses. To identify the cached responses you just need to check the presence of `x-request-cache` in the response headers of the r
```suggestion
Appbase.io sets the `X-Request-Cache` header as `true` for cached responses, i.e. when caching is enabled and the request was found within the cache.
```

@bietkul You can add a screenshot from Postman for this.

2021-04-13 00:11 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +## Clear Cache
```suggestion
## Evict Cache
```

2021-04-20 08:18 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +The memory limit for the cached requests in MB(s). The default value is 128MB. It can go up to 4000MB(4GB). Appbase.io uses a cache eviction policy to remove costly requests automatically once it rea
@bietkul This isn't addressed.

2021-04-20 08:19 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +Appbase.io sets the `x-request-cache` header as `true` for cached responses. To identify the cached responses you just need to check the presence of `x-request-cache` in the response headers of the r
@bietkul This also isn't addressed.

2021-04-20 08:19 UTC, siddharthlatest commented on content/docs/speed/cache-management.md
> +Appbase.io sets the `x-request-cache` header as `true` for cached responses. To identify the cached responses you just need to check the presence of `x-request-cache` in the response headers of the r
@bietkul This also isn't addressed.

2021-04-20 08:43 UTC, bietkul commented on content/docs/speed/cache-management.md
> +The memory limit for the cached requests in MB(s). The default value is 128MB. It can go up to 4000MB(4GB). Appbase.io uses a cache eviction policy to remove costly requests automatically once it rea
@siddharthlatest I've updated the content and included that part into `evict cache` section.
https://i.imgur.com/caZ5mAj.png

2021-04-20 11:51 UTC, siddharthlatest commented on src/pages/index.js
> +													'Cache search requests to boost the speed.',
```suggestion
													'Blazing ⚡️ Elasticsearch search performance with appbase.io cache,
```

2021-04-20 11:51 UTC, siddharthlatest approved these changes

2021-04-20 11:51 UTC, siddharthlatest commented on src/pages/index.js
> +													'Blazing ⚡️ Elasticsearch search performance with appbase.io cache,
```suggestion
													'Blazing ⚡️  search performance with appbase.io cache,
```

2021-04-20 11:51 UTC, merged