React-Searchbox: focusShortcuts, autofocus, addonBefore, addonAfter props added
appbaseio/Docs pull request #193
Opened 2021-05-11 23:56 UTC by mohdashraf010897

**Description** : focusShortcuts, autofocus, addonBefore, addonAfter props newly added to enhance the searchbox ui.

Notion Link: [Click Here!](https://www.notion.so/appbase/Support-searchbox-focus-with-keyboard-shortcut-3010b391595d4d0495a65e99f9591f9a)

2021-05-25 14:14 UTC, bietkul requested changes
@mohdashraf010897 Check the comments on `react-searchbox` and update docs everywhere. Did you add any new inner class in the lib?

2021-05-25 14:14 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +A list of keyboard shortcuts that focus the search box. Accepts key names and key codes. Compatible with key combinations separated using '+'. Defaults to `['/']`.
@mohdashraf010897 No mention of `hotkeys-js`?

2021-05-25 14:14 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +A list of keyboard shortcuts that focus the search box. Accepts key names and key codes. Compatible with key combinations separated using '+'. Defaults to `['/']`.
Also, add the default behavior.

2021-05-25 14:14 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **addonBefore** `string|JSX` [optional] The label text displayed before (on the left side of) the searchbox input field.
It is not about the `label text`. Users can use it to render additional actions. For example, add a custom search icon at the left and hide the default search icon.
Share the example snippet with a screenshot.

2021-05-25 14:14 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **addonAfter** `string|JSX` [optional] The label text displayed after (on the right side of) the searchbox input field.
Update definition. Add an example snippet to add a custom search icon at the right.

2021-05-25 14:14 UTC, bietkul commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **expandSuggestionsContainer** `boolean` [optional] When set to false the width of suggestions dropdown container is limited to the width of searchbox input field. Defaults to `true`.
@mohdashraf010897 You can add a screenshot.

2021-06-19 03:48 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +A list of keyboard shortcuts that focus the search box. Accepts key names and key codes. Compatible with key combinations separated using '+'. Defaults to `['/']`.
Done

> -   **focusShortcuts** `Array<string | number>` [optional]
A list of keyboard shortcuts that focus the search box. Accepts key names and key codes. Compatible with key combinations separated using '+'. Defaults to `['/']`.
> Note
>1. By default, pressing `'/'` would focus the search box.
>2. The `hotkeys-js` library needs to be installed manually when using combinations in `focusShortcuts` prop, eg: 'cmd+b', 'ctrl+q', etc, without which only single key shortcuts would work if passed in the prop, eg: From among ['/', 'b', '#', 'ctrl+r'], only '/', 'b', '#' would work without hotkey-js installation.

2021-06-19 04:54 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **expandSuggestionsContainer** `boolean` [optional] When set to false the width of suggestions dropdown container is limited to the width of searchbox input field. Defaults to `true`.
Done 
<img src'https://i.imgur.com/x3jF23m.png" />

2021-06-19 04:58 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **addonAfter** `string|JSX` [optional] The label text displayed after (on the right side of) the searchbox input field.
done
`-   **addonBefore** `string|JSX` [optional] The HTML markup displayed before (on the left side of) the searchbox input field. Users can use it to render additional actions/ markup, eg: a custom search icon hiding the default.
<img src="https://i.imgur.com/Lhm8PgV.png" style="margin:0 auto;display:block;"/>
```jsx
 <SearchBox
        showIcon={false}
        addonBefore={
          <img
            src="https://img.icons8.com/cute-clipart/64/000000/search.png"
            height="30px"
          />
        }
        id="search-component"
        ...
         />
```
`

2021-06-19 04:58 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-searchbox/searchbox.md
> +-   **addonBefore** `string|JSX` [optional] The label text displayed before (on the left side of) the searchbox input field.
done
`-   **addonBefore** `string|JSX` [optional] The HTML markup displayed before (on the left side of) the searchbox input field. Users can use it to render additional actions/ markup, eg: a custom search icon hiding the default.
<img src="https://i.imgur.com/Lhm8PgV.png" style="margin:0 auto;display:block;"/>
```jsx
 <SearchBox
        showIcon={false}
        addonBefore={
          <img
            src="https://img.icons8.com/cute-clipart/64/000000/search.png"
            height="30px"
          />
        }
        id="search-component"
        ...
         />
```
`

2021-06-21 05:25 UTC, bietkul approved these changes

2021-06-23 18:29 UTC, bietkul approved these changes

2021-06-23 18:29 UTC, merged