vue: docs updated for range-input component
appbaseio/Docs pull request #195
Opened 2021-05-19 11:43 UTC by anik-ghosh-au7

Description - `RangeInput` component added in vue-searchbox

please look into this PR for further reference - https://github.com/appbaseio/vue-playground/pull/28

2021-06-02 22:33 UTC, bietkul requested changes

2021-06-02 22:33 UTC, bietkul commented on content/docs/reactivesearch/vue/range/RangeInput.md
> +-   **componentStyle** `Object` [optional]
@anik-ghosh-au7 Remove it for now

2021-06-02 22:33 UTC, bietkul commented on content/docs/reactivesearch/vue/range/RangeInput.md
> +		:validateRange="[start, end] => {
@anik-ghosh-au7 Do you think that if it is the correct syntax?

2021-06-02 22:33 UTC, bietkul commented on content/docs/reactivesearch/vue/range/RangeInput.md
> +							data_field: 'this is a test',
```suggestion
							price: 1000,
```

2021-06-02 22:34 UTC, bietkul commented
@anik-ghosh-au7 Embed the codesandbox link. Add an example in Repo.

2021-06-03 12:07 UTC, anik-ghosh-au7 commented
@bietkul I have done the updates as you have mentioned

2021-06-03 15:09 UTC, bietkul approved these changes
lgtm 👍

2021-06-03 19:40 UTC, merged