feat(SearchBox-Headless,react & vue)/add enableTelemetry def
appbaseio/Docs pull request #221
Opened 2021-08-09 15:06 UTC by mohdashraf010897

**PR Type**: Feature

**Description**: Adding telemetry support in RS apps, adds an `enableTelemetry` property in `appbaseConfig` object to switch off telemetry.

[🔗  Implementation PR](https://github.com/appbaseio/searchbox/pull/116)

2021-09-21 09:46 UTC, siddharthlatest requested changes
Follow the formatting fixes that we've made in #220.

2021-09-21 09:46 UTC, siddharthlatest commented on content/docs/reactivesearch/react-native-searchbox/searchbase.md
> +     -   **enableTelemetry** `Boolean` When set to `false`, disable the telemetry. Defaults to `true`.
@mohdashraf010897 There looks like an indent issue with the PR here, can you fix this?

2021-09-21 10:04 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-native-searchbox/searchbase.md
> +     -   **enableTelemetry** `Boolean` When set to `false`, disable the telemetry. Defaults to `true`.
https://github.com/appbaseio/Docs/pull/221/commits/97f5892385ed283fa7f9dad84b1584cefed51eae

2021-09-21 10:04 UTC, mohdashraf010897 commented on content/docs/reactivesearch/react-native-searchbox/searchbase.md
> +     -   **enableTelemetry** `Boolean` When set to `false`, disable the telemetry. Defaults to `true`.
fixed here @siddharthlatest

2021-09-23 16:15 UTC, siddharthlatest approved these changes

2021-09-23 16:15 UTC, merged