feat: docs addition for RS SearchBox
appbaseio/Docs pull request #245
Opened 2021-11-10 16:01 UTC by mohdashraf010897

**PR Type** For ReactiveSearch, we created a Searchbox component. This PR adds docs support for the same.

- [x]  Searchbox support in React

Implementation  PR: https://github.com/appbaseio/reactivesearch/pull/1806

[Notion Link](https://www.notion.so/appbase/8648760a66da4dcfa5ebcefd2e439ddc)

2021-11-22 17:05 UTC, siddharthlatest requested changes

2021-11-22 17:05 UTC, siddharthlatest commented on content/docs/reactivesearch/v3/search/searchbox.md
> +	componentId="SearchBoxSensor"
@mohdashraf010897 Check the indent here.

2021-11-22 17:05 UTC, siddharthlatest commented on src/data/sidebars/web-reactivesearch.yaml
> +            - title: SearchBox
@mohdashraf010897 Move this above DataSearch.

2021-11-22 17:05 UTC, siddharthlatest commented on content/docs/reactivesearch/v3/search/searchbox.md
> +<iframe src="https://codesandbox.io/embed/github/appbaseio/reactivesearch/tree/next/packages/web/examples/DataSearch" style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
@mohdashraf010897 We should update this example before merging this PR.

2022-01-03 07:35 UTC, bietkul requested changes

2022-01-03 07:35 UTC, bietkul commented on content/docs/reactivesearch/v3/search/searchbox.md
> +> Note: The `fieldWeights` property has been marked as deprecated in <b>v3.21.0</b> of ReactiveSearch and <b>v7.47.0</b> of Appbase and would be removed in the next major release. We recommend you to
```suggestion
> Note: The `fieldWeights` property has been marked as deprecated in <b>v3.21.0</b> of ReactiveSearch and <b>v7.47.0</b> of Appbase and would be removed in the next major release. We recommend you to use the [dataField](/docs/search/reactivesearch-api/reference/#datafield) property to define the weights.

```

2022-01-03 07:36 UTC, bietkul requested changes

2022-01-03 07:36 UTC, bietkul commented on content/docs/reactivesearch/v3/search/searchbox.md
> +    > This property only works with [ReactiveSearch API](/docs/search/reactivesearch-api/) i.e when `enableAppbase` is set to `true` in `ReactiveBase` component.
```suggestion
    > Note:
    >
    > This property only works with [ReactiveSearch API](/docs/search/reactivesearch-api/) i.e when `enableAppbase` is set to `true` in `ReactiveBase` component.
   
```

2022-01-03 07:36 UTC, merged