feat(react/vue/mongo): added csb links for examples with updated lib
appbaseio/Docs pull request #253
Opened 2021-11-27 09:31 UTC by mohdashraf010897

**PR Type** `Feature`

**Description**
- Added updated CSB's for examples dependent upon searchbox libs (react/ vue).
- Added Geo example for Atlas React [here](https://docs.appbase.io/docs/reactivesearch/atlas-search/search-examples-with-react/#geo-examples).

2021-11-28 15:05 UTC, siddharthlatest requested changes
Overall, this is looking good 👌

We can fix the following things:

- [ ] Range example: Add a UI element in the result item to show the accommodates value
- [ ] Search example: Search Icon with each item is missing (on the left)
  - [ ] scroll shouldn't be needed for default rendering up to 10 elements
  - [ ] Autocomplete example: Remove the description field, it's adding too much noise
- [ ] Map example: Z-index issue
  - [ ] we can avoid showing the accommodates value in the map marker pin. It can be confused with clustering.
  - [ ] show the image(s) in the popover if possible

2021-11-29 10:24 UTC, mohdashraf010897 commented
> Overall, this is looking good 👌
> 
> We can fix the following things:
> 
> * [x]  Range example: Add a UI element in the result item to show the accommodates value
> * [x]  Search example: Search Icon with each item is missing (on the left)
>   
>   * [x]  scroll shouldn't be needed for default rendering up to 10 elements
>   * [x]  Autocomplete example: Remove the description field, it's adding too much noise
Fixed in here :https://github.com/appbaseio/searchbox/pull/144#issuecomment-981472585, released @appbase/(react/ vue)-searchbox v1.6.0-alpha.1 for the purpose.

2021-11-29 13:02 UTC, mohdashraf010897 commented
> * [x]  Map example: Z-index issue
>   
>   * [x]  we can avoid showing the `accommodates` value in the map marker pin. It can be confused with clustering.
>   * [x]  show the image(s) in the popover if possible

Fixed here 👉  https://github.com/appbaseio/reactivesearch/pull/1816/commits/6f8dc96b899fb400f5d6c84d7234745fe11c7767

2021-11-29 17:13 UTC, siddharthlatest approved these changes

2021-11-29 17:15 UTC, merged