docs: add usage for props like showRadio, displayAsVertical, showSearch
appbaseio/Docs pull request #342
Opened 2022-07-28 10:12 UTC by SavvyShah

- Add usage of props like showRadio, displayAsVertical, showSearch for `SingleDataList` and `TabDataList`.
- Some content changes for `TabDataList`.

2022-07-28 10:49 UTC, mohdashraf010897 requested changes

2022-07-28 10:49 UTC, mohdashraf010897 commented on content/docs/reactivesearch/v3/list/tabdatalist.md
> +    Filter tabs using a search bar
use smallcase for `Filter` ---> 'filter'

2022-07-28 10:49 UTC, mohdashraf010897 commented on content/docs/reactivesearch/v3/list/tabdatalist.md
> +    show radio buttons with tabs just as we are using a `SingleDataList`
content could be _show radio buttons instead of tabs_

2022-07-28 10:49 UTC, mohdashraf010897 commented on content/docs/reactivesearch/v3/list/tabdatalist.md
>      layout tabs for the list vertically instead of horizontally.
matter could be _layout tabs vertically. Defaults to `false`_

2022-08-01 02:37 UTC, siddharthlatest commented on content/docs/reactivesearch/v3/list/tabdatalist.md
> +-   separate pages of content on basis of category
```suggestion
-   display result tabs based on a value classification
```

2022-08-01 02:38 UTC, siddharthlatest approved these changes

2022-08-01 02:39 UTC, merged