feat: featured suggestions in vue
appbaseio/Docs pull request #397
Opened 2023-05-21 15:10 UTC by SavvyShah

Documentation updated after adding featured suggestions support for VueJS

[Reactivesearch PR](https://github.com/appbaseio/reactivesearch/pull/2221)

2023-05-26 05:50 UTC, mohdashraf010897 approved these changes
@SavvyShah Resolve the conflicts

2023-05-26 05:55 UTC, mohdashraf010897 requested changes
- searchboxId prop is missing here. (the change has to happen in React version also)
- Can we add a link to a featuredSuggestions example that we have?
- We are not using netlify anymore, please change the domain to use vercel.
-> https://reactivesearch-vue.vercel.app/

2023-05-26 05:55 UTC, mohdashraf010897 commented on content/docs/reactivesearch/vue/search/SearchBox.md
> +	    enableFeaturedSuggestions
@SavvyShah 

- `searchboxId` prop is missing here. (the change has to happen in React version also)
- Can we add a link to a featuredSuggestions example that we have?

2023-05-26 05:55 UTC, mohdashraf010897 commented on content/docs/reactivesearch/vue/search/SearchBox.md
>  <a href="https://reactivesearch-vue-playground.netlify.com/?selectedKind=Search%20Components%2FSearchBox&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0" target="_blank">SearchBox with def
@SavvyShah We are not using netlify anymore, please change the domain to use vercel.

-> https://reactivesearch-vue.vercel.app/

2023-07-21 05:29 UTC, mohdashraf010897 approved these changes
@siddharthlatest Would recommend you to have a look at the sentence formulation, probably need  some improvisation on that.

2023-07-23 10:24 UTC, siddharthlatest approved these changes

2023-07-23 10:24 UTC, siddharthlatest commented on content/docs/reactivesearch/react/search/searchbox.md
> +Defaults to `false`. When set to `true`, shows frequent user queries which on click instantly shows the answer for the query. FAQs are set from the dashboard by creating a Searchbox. Hence they requi
```suggestion
Defaults to `false`. When set to `true`, show frequently asked user questions as configured via the ReactiveSearch dashboard. When this property is set as `true`, `searchboxId` is required to be passed.
```

2023-07-23 10:24 UTC, siddharthlatest commented on content/docs/reactivesearch/react/search/searchbox.md
> +- size: `number` maximum number of faq suggestions fetched per section.
```suggestion
- size: `number` maximum number of FAQ suggestions to be fetched per section
```

2023-07-31 09:25 UTC, siddharthlatest approved these changes

2023-07-31 09:25 UTC, merged