feat: integration with GoogleAnalytics
appbaseio/Docs pull request #62
Opened 2019-10-11 14:08 UTC by ShahAnuj2610

how this can be integrated with `Vue` is left. maybe someone can help me with it.

2019-10-13 23:05 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +The base library components doesn't provide a built-in widget to implement analytics with other providers.
s/doesn't/don't (since components is plural)

2019-10-13 23:05 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +-   set up the Google Analytics library in your page
in your `search app` (instead of page)

2019-10-13 23:07 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +-   set up the Google Analytics library in your page
Please link to their installation page.

2019-10-13 23:09 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +Once the GA library is installed on your website, look below how Google Analytics can be integrated with different libraries
`look below how` should be `follow the steps below on how`

2019-10-13 23:11 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +##Integrating With Libraries
Title should be: "Setup The Search State Change Listener" based on the two steps you highlighted above. If this isn't accurately worded, also change the referenced bullet point's text.

2019-10-13 23:12 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +##Integrating With Libraries
Add the following line before starting the library specific sections.

"Setting the search state change listener depends on how your search app is setup. If you are using one of the appbase.io libraries, you can refer to the sections below on how you can do this.

2019-10-13 23:13 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +Track any component's state using `StateProvider` component as below. Read more about `StateProvider` [here](https://docs.appbase.io/docs/reactivesearch/v3/advanced/stateprovider/):
`StateProvider [here]` should be `StateProvider over here`.

2019-10-13 23:14 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +If you want to track only your `DataSearch` component, you can add the following. Read more about `DataSearch` [here](https://docs.appbase.io/docs/reactivesearch/v3/search/datasearch/):
Rephrase: If you only want to track your searchbox and you are using the [`DataSearch`](link to doc) component for it, you can do the following.

2019-10-13 23:15 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +Check the API docs for `React SearchBox` [here](https://docs.appbase.io/docs/reactivesearch/react-searchbox/apireference/).
`React SearchBox [here]` becomes `React SearchBox over [here]`.

2019-10-13 23:15 UTC, siddharthlatest commented on content/docs/analytics/GoogleAnalytics.md
> +```
@ShahAnuj2610 You're missing the section for Vue.JS ReactiveSearch.

2019-10-13 23:16 UTC, siddharthlatest requested changes
See the specific comments.

2019-10-14 06:16 UTC, ShahAnuj2610 commented on content/docs/analytics/GoogleAnalytics.md
> +-   set up the Google Analytics library in your page
it's linked on `L22`

2019-10-14 22:35 UTC, siddharthlatest approved these changes

2019-10-14 22:36 UTC, merged