feat: vue-searchbox getting started and api-ref
appbaseio/Docs pull request #68
Opened 2019-10-21 07:38 UTC by ShahAnuj2610

2019-11-04 13:01 UTC, bietkul requested changes
@ShahAnuj2610 Remove `searchStateHeader` from analyticsConfig.

2019-11-04 13:10 UTC, ShahAnuj2610 commented
> @ShahAnuj2610 Remove `searchStateHeader` from analyticsConfig.

done

2019-11-06 11:47 UTC, siddharthlatest requested changes

2019-11-06 11:47 UTC, siddharthlatest commented on content/docs/reactivesearch/vue-searchbox/quickstart.md
> +meta_title: 'QuickStart to React SearchBox'
@ShahAnuj2610 The doc is referring to React instead of Vue.

2019-11-06 11:47 UTC, siddharthlatest commented on content/docs/reactivesearch/vue-searchbox/apireference.md
> +meta_title: 'QuickStart to React SearchBox'
@ShahAnuj2610 Doc is referring to React instead of Vue.

2019-11-06 11:56 UTC, siddharthlatest commented on content/docs/reactivesearch/vue-searchbox/quickstart.md
> +[vue-searchbox](https://github.com/appbaseio/vue-searchbox) - A lightweight Vue search library with some common utilities.
@ShahAnuj2610 Update description. The `React` doc for getting started also needs an updated description.

2019-11-06 12:05 UTC, siddharthlatest approved these changes

2019-11-06 12:05 UTC, merged