feat: add query suggestions docs
appbaseio/Docs pull request #79
Opened 2019-11-05 17:49 UTC by bietkul

2019-11-06 15:42 UTC, siddharthlatest requested changes
See the TODO notes.

2019-11-06 16:37 UTC, siddharthlatest requested changes
See the specific comments.

2019-11-06 16:37 UTC, siddharthlatest commented on content/docs/analytics/QuerySuggestions.md
> +// TODO: Add screenshot of Suggestions UI
@bietkul This should be easy. Do it after the suggestions UI changes.

2019-11-06 16:37 UTC, siddharthlatest commented on content/docs/analytics/QuerySuggestions.md
> +// TODO: The example is not complete
@bietkul We will deal with this in a separate issue. I would recommend trying the below demo once. Does this work on partial suggestions terms? It seems that we should have search analyzers enabled on the query suggestions index.

2019-11-07 13:10 UTC, siddharthlatest commented on content/docs/analytics/QuerySuggestions.md
> +// TODO: The example is not complete
We actually handle this. Use both `key`^3 and `key.autosuggest`^1 and use weights appropriately.

2019-12-03 04:28 UTC, bietkul commented
@siddharthlatest Can you review & merge it.

2019-12-11 08:17 UTC, siddharthlatest approved these changes

2019-12-11 08:17 UTC, merged