Feat/aggregations
appbaseio/Docs pull request #81
Opened 2019-11-11 12:39 UTC by ShahAnuj2610

2019-11-18 10:45 UTC, bietkul requested changes

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/vue/search/DataSearch.md
> +    > If you are using an app with elastic search version less than 6, then you have to handle error manually using **renderError** slot.
This sentence seems like that the user will have an error if using the es6 apps disregarding of they are using `aggregationField` or not.
Just mention that this prop doesn't work with es6 apps (no support of composite aggregation), it'll throw the error which can be handled by using `onError` or `renderError`.

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/vue/search/DataSearch.md
> +    	slot="renderAllSuggestions"
@ShahAnuj2610 You also need to add the `aggregationField` in the docs of `renderAllSuggestions`.

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/vue/result/ReactiveList.md
> +    > If you are using an app with elastic search version less than 6, then you have to handle error manually using **renderError** slot.
Read the comment for `data-search`.

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/v3/search/datasearch.md
> +    > If you are using an app with elastic search version less than 6, then you have to handle error manually using **renderError** prop.
Check comments for data search for vue.

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/v3/search/categorysearch.md
> +-   **aggregationField** `String` [optional]
Update `render` prop docs.

2019-11-18 10:45 UTC, bietkul commented on content/docs/reactivesearch/v3/result/reactivelist.md
> +    > If you are using an app with elastic search version less than 6, then you have to handle error manually using **renderError** prop.
Update this everywhere.

2019-11-18 11:39 UTC, ShahAnuj2610 commented
@bietkul have made the changes

2019-11-21 18:44 UTC, bietkul approved these changes

2019-11-21 18:46 UTC, merged